### ISSUE TITLE
`Const(obj, shape)` should use RFC 9 to cast `obj` to `shape`

### ISSUE THREAD

**Issue by whitequark** [amaranth-lang/amaranth#1061]
There was [previous discussion](https://libera.irclog.whitequark.org/amaranth-lang/2024-01-29#1706564973-1706566225;) of this feature.

**Comment by whitequark** [comment]
@zyp has mentioned they will write the RFC unless someone else picks it up.

**Comment by wanda-phi** [comment]
This has an RFC now: amaranth-lang/rfcs#42
