### ISSUE TITLE
PySim VCDWriter is useless with `io.StringIO`

### ISSUE THREAD

**Issue by whitequark** [amaranth-lang/amaranth#1107]
It unconditionally calls `close` on the VCD and that destroys the `StringIO` object. Questionable design of the latter, perhaps, but we have to live with it.

~Not entirely clear what to do with it. I suggest just special-casing `io.StringIO` for specifically `write_vcd(vcd_file=)`. Though, there could be a similar issue with a `tempfile.TemporaryFile` or `tempfile.SpooledTemporaryFile`, so maybe a `close_vcd_file=True` argument would work better.~

It should only close IO objects that it had opened itself.

**Comment by zyp** [comment]
I would argue that the sanest solution is for it to only close file objects it has opened itself, i.e. when passed a filename.

When the caller passes a file object, whether it's a `StringIO`, a regular file or anything else, leave it to the caller to deal with closing it.

**Comment by whitequark** [comment]
> I would argue that the sanest solution is for it to only close file objects it has opened itself, i.e. when passed a filename.

You're completely right.
