### ISSUE TITLE
Tracking issue for RFC 51: Add `ShapeCastable.from_bits` and `amaranth.lib.data.Const`

### ISSUE THREAD

**Issue by wanda-phi** [amaranth-lang/amaranth#1187]
- RFC PR: amaranth-lang/rfcs#51
- Implementation PR: https://github.com/amaranth-lang/amaranth/pull/1202
- Deprecation PR (for making `ShapeCastable.from_bits` non-optional): #1394

**Comment by whitequark** [comment]
When `ShapeCastable.from_bits` is made mandatory, `lib.data` docs must be updated to remove a few "if from_bits is implemented" clauses.
