### ISSUE TITLE
Signals with private names

### ISSUE THREAD

**Issue by whitequark** [amaranth-lang/amaranth#1223]
In some cases it is desirable to create a signal with a name that doesn't show up in the waveform viewer, such as when a signal is created to hold the results of intermediate computations, or to change shape, and it would just add noise. I propose adding a notion of a "private signal name".

I suggest changing naming rules so that `Signal(name="")` creates a signal with a private name. Such a signal is translated to a private wire in RTLIL (with a `$\d+` name), doesn't get displayed in the waveform viewer, and so on.

---

The FSM ongoing signals (not the state signal) should be changed to have private names in the 0.5 milestone.

**Comment by tpwrules** [comment]
Would this ever be the default for a signal generated by Amaranth, or would a user always have to create it explicitly?

**Comment by whitequark** [comment]
> Would this also be the default for some signals generated by Amaranth

Only the ones that are implementation details (currently just `with m.FSM()` but I think we might have others later).

**Comment by tpwrules** [comment]
I think this should be straightforward, I will try to cook up an implementation this weekend and update by Monday.

**Comment by whitequark** [comment]
Thanks!
