### ISSUE TITLE
Tracking issue for RFC 62: The `MemoryData` class.

### ISSUE THREAD

**Issue by wanda-phi** [amaranth-lang/amaranth#1241]
- RFC PR: amaranth-lang/rfcs#62
- Implementation:
  - `MemoryData` class: #1256
  - `MemoryData._Row` class: #1271 
  - Documentation: #1294

**Comment by whitequark** [comment]
We need *some* documentation; at least, enough to know that to manipulate memory rows in simulation you need to do e.g. `memory.data[0].eq(1)`. Currently `memory.data` is completely undocumented.
