### ISSUE TITLE
`execute_local_docker()` does not forward SIGINT/ctrl+c to docker subprocess

### ISSUE THREAD

**Issue by polymerizedsage** [amaranth-lang/amaranth#1246]
I use the `execute_local_docker()` build command almost exclusively in my current project. I have noticed that if I ctrl+c a build the docker subprocess that is spawned by Amaranth doesnt exit. This is undesirable because it can lead to mistakenly spawning two docker containers which are both actively modifying the build directory.

**Comment by whitequark** [comment]
Ah yeah that's unpleasant. Want to fix it? It will require catching `KeyboardInterrupt`, I think.

**Comment by polymerizedsage** [comment]
Yep should be a pretty simple fix. Ill PR when I get a chance, probably tomorrow.

**Comment by whitequark** [comment]
@polymerizedsage Have you been able to fix this issue?

**Comment by polymerizedsage** [comment]
gonna pretend I didnt forget about this and instead have just been lazy on opening the PR. Heres the fix:
`subprocess.check_call()` should handle catching the `KeyboardInterrupt` and sending SIGKILL/SIGTERM but that doesnt seem to work well for docker container processes. Having the container run an interactive shell with `-it` instead means the command running in the container will properly receive the ctrl-c input.
