### ISSUE TITLE
Indexing into signals with layouts could be improved

### ISSUE THREAD

**Issue by isabelburgos** [amaranth-lang/amaranth#1375]
Motivating example:
If you have `s = Signal(Layout)`, you can index a specific field with `s.field` or `s[field]`;  or index a slice with `s.as_value()[0:4]`. If you try to index it directly as `s[0:4]` you get `KeyError: slice(0, 4, None)`. 

This is a bit of a sharp edge for a new user because `s[0:4]` looks like valid amaranth syntax and would be valid for `s = Signal(8)`. A useful piece of context not provided by the error message is that `s.as_value()[0:4]` is how you would accomplish the intention of `s[0:4]`.

Possible resolutions: 
1) Since layouts already have a custom `__getitem__`  method, an extra error message could be added there, along the lines of:
```python
 if isinstance(key, slice): 
      raise KeyError("Signals with layouts cannot be indexed with slices, use signal.as_value()")
```
2) Make it possible to index into a signal directly, so that `s[0:4]` and `s.field` are both valid. Since layout members must be strings, there shouldn't be any possible collisions between integer slices and layout members (ie, you could have a field named `"0:4"` but not a field named `0:4`. I'm not sure exactly what this implementation could look like.

3) Do nothing. The existing Amaranth documentation already explains all of this.

**Comment by whitequark** [comment]
I explicitly rejected (2) during the design of `lib.data` but (1) seems like a clear improvement, with a slightly different message perhaps. I'm happy to review a PR adding it.
