### ISSUE TITLE
`stream.Signature` should allow setting the init value for the payload

### ISSUE THREAD

**Issue by whitequark** [amaranth-lang/amaranth#1404]
This for example does not work:

```python
class BitSerializer(wiring.Component):
    def __init__(self, *, width, length):
        self._length = length

        super().__init__({
            "shift": In(1),
            "stream": In(stream.Signature(data.StructLayout({
                "o":  data.ArrayLayout(width, length),
                "oe": 1
            })), init={"payload": {"oe": 1}}),
            "buffer": Out(io.FFBuffer.Signature("o", width)),
        })
```

but could be valuable for the same reason `io.Buffer.Signature`'s `oe` member has `init=1`.

**Comment by wanda-phi** [comment]
doing it with the proposed syntax is not possible with current `lib.wiring` (a member of signature type with `init` will be rejected)

what do you think about `stream.Signature(..., payload_init={"oe": 1})` instead?

**Comment by whitequark** [comment]
Let's bikeshed `payload_init=` vs `init=` on the next meeting.

**Comment by whitequark** [comment]
We have [discussed](https://libera.irclog.whitequark.org/amaranth-lang/2024-07-01#1719852888-1719853716;) this issue on the 2024-07-01 weekly meeting. We have decided to go with `payload_init=`.
