### ISSUE TITLE
Arch Linux installation instructions are incorrect

### ISSUE THREAD

**Issue by meithecatte** [amaranth-lang/amaranth#1482]
The documentation suggests running the following to install Amaranth on Arch Linux:

```
$ sudo pacman -S python-amaranth
```

However, this package does not exist in the Arch repositories:

```
error: target not found: python-amaranth
```

The only mention of such a package I've been able to find is [on the AUR](https://aur.archlinux.org/packages/python-amaranth) – this is a different thing than the actual Arch repositories, as users must build the binary packages manually, based on the PKGBUILD provided, or use a third-party tool that automates this process.

**Comment by whitequark** [comment]
What should the instructions say?

**Comment by meithecatte** [comment]
You could give the following instructions:
```
$ git clone https://aur.archlinux.org/python-amaranth.git
$ cd python-amaranth
$ makepkg -si
```

However, I don't necessarily think this is a good idea. I'd mention that the AUR package exists, and steer users who don't know what to do with that info towards the normal pip installation route.

**Comment by whitequark** [comment]
Mm, I guess we should probably just remove the Arch instructions then; it seems like those who want to go the native route already know what to do...
