### ISSUE TITLE
How to cite Amaranth?

### ISSUE THREAD

**Issue by k0nze** [amaranth-lang/amaranth#1545]
I'm working on a publication using Amaranth, what would be the correct way to cite the Amaranth project?

**Comment by k0nze** [comment]
For example, the RISC-V-TLM repository provides a BibTeX string https://github.com/mariusmm/RISC-V-TLM to the publication related to the repository. I guess if there is no publication for Amaranth, citing the GitHub repository will suffice.

**Comment by whitequark** [comment]
Yes, linking to the repository seems fine.
