### ISSUE TITLE
Adding platform to Simulator class

### ISSUE THREAD

**Issue by YusufCelik** [amaranth-lang/amaranth#1547]
How is platform passed to a simulation? 
Otherwise during a testbench, the platform will amount to None and platform.request in elaborate will not work.
As an alternative, I am currently doing this (overwriting init to accept a platform argument that is passed to Fragment.get):

```
def __init__(self, toplevel, *, engine="pysim", platform=None):
    if isinstance(engine, type) and issubclass(engine, BaseEngine):
        pass
    elif engine == "pysim":
        from amaranth.sim.pysim import PySimEngine

        engine = PySimEngine
    else:
        raise TypeError(
            f"Value {engine!r} is not a simulation engine class or a simulation engine name"
        )

    self._design = Fragment.get(toplevel, platform=platform).prepare()
    self._engine = engine(self._design)
    self._clocked = set()
    self._running = False


Simulator.__init__ = __init__

sim = Simulator(dut, platform=platform)
```

Assuredly, there should be an easier way?

**Comment by whitequark** [comment]
We've previously [discussed](https://github.com/amaranth-lang/rfcs/pull/48) this functionality and decided to not implement it.

I believe you've been shown this on IRC, but for the time being you can use `Fragment.get(elaboratable, platform)` to avoid patching core Amaranth code.
