### ISSUE TITLE
Support transparent ports with RE

### ISSUE THREAD

**Issue by nmigen-issue-migration** [amaranth-lang/amaranth#18]
<a href="https://github.com/whitequark"><img src="https://avatars1.githubusercontent.com/u/54771?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [whitequark](https://github.com/whitequark)**
_Tuesday Jan 01, 2019 at 03:26 GMT_
_Originally opened as https://github.com/m-labs/nmigen/issues/16_

----

This is currently not done because of a quirk (bug?) in Yosys: https://github.com/YosysHQ/yosys/issues/760. This is not right and affects user designs as the `en` signal is a constant and cannot be assigned to: https://github.com/m-labs/nmigen/blob/d78e6c155b6de72ab56f7cb123bc2b7cdb8f6b04/nmigen/hdl/mem.py#L89-L92.

**Comment by wanda-phi** [comment]
This has been fixed by #893 and can be closed.

**Comment by whitequark** [comment]
Nice!
