### ISSUE TITLE
Memory port transparency model is flawed

### ISSUE THREAD

**Issue by nmigen-issue-migration** [amaranth-lang/amaranth#216]
<a href="https://github.com/whitequark"><img src="https://avatars1.githubusercontent.com/u/54771?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [whitequark](https://github.com/whitequark)**
_Friday Sep 20, 2019 at 18:04 GMT_
_Originally opened as https://github.com/m-labs/nmigen/issues/216_

----

Investigating #172, it appears that there are two major issues with the way port transparency is handled.
  1. Transparent read ports should not be the default, since it is expensive. On many platforms (e.g. iCE40), fabric logic will need to be inserted. On other platforms (e.g. Xilinx), non-transparent ports have a much larger set of configurations with well-defined behavior. Transparency between different clock domains is impossible with BRAMs and will result in a (silent) failure during synthesis.
  2. Transparency should not be requested *in general*, but rather for a specific write port (in the same domain). It does not make sense to request a "fully" transparent read port for a true dual-port RAM with write ports in different domains. It does make sense to request a read port transparent only wrt one specific write port for a true dual-port RAM with write ports in the same domain (this is implementable in Xilinx) and a read port transparent wrt both write ports for a true dual-port RAM with write ports in the same domain (this is not directly implementable in any FPGA arch I know, but is useful for e.g. superscalar CPU register files).

I propose to remove `transparent` completely, replacing it with a `transparent_for=[write_ports]` argument. The default (when this argument is not specified) would be "transparent for no write ports" for synchronous read ports, and "transparent for all ports" for asynchronous read ports. It would not be possible to specify a non-default value for an asynchronous read port.

The lowering to RTLIL would be the same as today, with the selected write port ignored (beyond checking that the domain is compatible),

**Comment by galibert** [comment]
If there a way to say "I'm not going to read and write in the same cycle ever, so do what's best given the platform"?

**Comment by whitequark** [comment]
No. Yosys doesn't support it.

**Comment by whitequark** [comment]
Yosys now supports a much better memory port transparency model.

This issue will be solved by https://github.com/amaranth-lang/rfcs/pull/45.
