### ISSUE TITLE
Accessing Memory objects with '[ ]' array syntax causes confusing build errors.

### ISSUE THREAD

**Issue by WRansohoff** [amaranth-lang/amaranth#340]
It sounds like it is only possible to access Memory data with square-bracket array syntax (`memory[ index ]`) during simulation.

But when I try to build a bitstream from a design which uses that syntax, it seems to cause an infinite loop in nMigen instead of printing an error. Interrupting the process results in some nested `LegalizeValue` exceptions which eventually point to:

    nmigen.back.rtlil.LegalizeValue: ((+ (sig addr) (const 2'd2)), range(0, 1028), ('[...]/nmigen/hdl/mem.py', 91))

It sounds like this can be fixed by using the Memory object's read/write ports [like the `examples/basic/mem.py` file](https://github.com/nmigen/nmigen/blob/master/examples/basic/mem.py) demonstrates, but an error message might help make that more discoverable. Thanks!

**Comment by FFY00** [comment]
Hum, shouldn't `RecursionError` be raised? I think it would be good to investigate why it isn't triggered.

**Comment by whitequark** [comment]
> Hum, shouldn't `RecursionError` be raised? I think it would be good to investigate why it isn't triggered.

Because it's not an infinite loop or recursion. It's just really slow.

**Comment by whitequark** [comment]
https://github.com/amaranth-lang/rfcs/pull/45 may address this issue if accepted.
