### ISSUE TITLE
Add option to suppress code generation comments

### ISSUE THREAD

**Issue by hansfbaier** [amaranth-lang/amaranth#572]
When generating code, almost every line has code generation comments.
While this is useful for debugging, it makes the code very hard to read.
Therefore it would be great to have a code generation option
to suppress those.

**Comment by hellow554** [comment]
hey @hansfbaier 
you seem to have been working on this issue (according to the three references commits here).
What is your status on this? Are you able to submit a PR?

**Comment by hansfbaier** [comment]
@hellow554 : I have this: https://github.com/hansfbaier/nmigen/commit/304ad1ffa2b64fe60cb709d9dad2cb9edaf9d87c
But I am hesitant to create a pull request, because whitequark seems opposed to having this functionality in nmigen,
see https://github.com/nmigen/nmigen/pull/573

**Comment by whitequark** [comment]
I think the functionality is fine, the implementation just needs to be improved. I apologize for my disproportionally intense reaction, @hansfbaier--I'll work something out to have this upstream.

**Comment by hansfbaier** [comment]
@whitequark  Thank you!
