### ISSUE TITLE
bad error message when giving Cat strings

### ISSUE THREAD

**Issue by anuejn** [amaranth-lang/amaranth#614]
`Cat` gives a `RecursionError` when giving it a string.
Probably `flatten` (from _util.py) should have special casing for strings to fix this. 

repro:
```python
from nmigen import Cat
Cat("test")
```

**Comment by whitequark** [comment]
I vaguely recall fixing something like that once--not sure what happened with that. In any case, yes, reasonable.

**Comment by whitequark** [comment]
Thanks for the report!
