### ISSUE TITLE
Extra Documentation Link

### ISSUE THREAD

**Issue by JosephBushagour** [amaranth-lang/amaranth#616]
I'm learning nMigen and I stumbled a bit because the community tutorials linked in docs/tutorial.rst (therefore also [here](https://nmigen.info/nmigen/latest/tutorial.html)) are great but slightly out of date (leading to some syntax issues). I wrote an up-to-date quick overview of the language [here](https://github.com/JosephBushagour/tour-of-nmigen), which, if added to the links in docs/tutorial.rst, could help people like me who are new to nMigen.

Thanks for all your work on the language!

**Comment by whitequark** [comment]
The documentation here is unfortunately outdated by now, and in any case first-party documentation is going to be complete soon, so I'm closing this.
