### ISSUE TITLE
Download link is wrong on https://nmigen.info/nmigen/latest/start.html

### ISSUE THREAD

**Issue by mattvenn** [amaranth-lang/amaranth#647]
https://nmigen.info/nmigen/latest/_code/up_counter.py is a 404

The link in the .rst leads hosted by github leads to:

https://github.com/nmigen/nmigen/blob/master/docs/_code/up_counter.py

which works. Is there a way to get the link to work for both github and read the docs?

**Comment by whitequark** [comment]
> Is there a way to get the link to work for both github and read the docs?

I don't know about _both_, but it was supposed to work on Sphinx as originally written. I'll take a look.
