### ISSUE TITLE
[RFC] Support `bytes` in `Value.cast`

### ISSUE THREAD

**Issue by modwizcode** [amaranth-lang/amaranth#673]
# Background 
It is frequently useful to directly assign byte string constants to a `Signal` or otherwise use them in a context where `ValueCastable`s are expected. This RFC proposes supporting this pattern in Amaranth by handling `bytes` values in `Value.cast`.

# Implementation
These values would be "lowered" to a `Const` containing the entire value of the `bytes` packed in little-endian byte order. This would thus produce a `Value` of `8*len(bytes)` bits. The goal here is not to use the minimal space for each value but to encode them in a useful way for debugging.

# Why?
One significant use for this is for debugging, allowing values that are easily recognized in traces or in printouts to be used directly. Currently each project desiring this capability has to implement it locally; this leads to a lot of replicated code. Otherwise it is simply a feature we have encountered the desire for on multiple occasions when dealing with ASCII constants in protocols and testbenches.

# Why not?
* Some users could theoretically find this confusing
* Not useful enough to justify
* Concerns over how the bytes end up packed (ordering)

**Comment by whitequark** [comment]
Thank you for filing this RFC, @modwizcode.

We [discussed](https://libera.irclog.whitequark.org/amaranth-lang/2023-02-13#1676310315-1676310976;) this RFC at the weekly meeting. We reached a rough consensus that while potentially convenient, the alternative (using `int.from_bytes(x, byteorder="little")`) doesn't bother anyone and the value of this addition to the language seems insufficient to justify the added complexity of adding another implicit conversion.

Therefore, I'm closing this RFC.
