### ISSUE TITLE
pyvcd version pin troubles

### ISSUE THREAD

**Issue by dragonmux** [amaranth-lang/amaranth#690]
pyvcd is currently pinned to version 0.2.2, while Arch and several projects built on top of Amaranth are already using version 0.3.x.

This has been causing us problems as pip doesn't very much like this - is there a good reason why Amaranth is forcing this older series of pyvcd, and if not can the pin please be updated to allow the newer minor?

We've been using Amaranth with version 0.3.0 (or newer revisions) allowed on our fork (for the OpenLANE/Caravel flow dev) without issue.

(ping @modwizcode as we had a chat with them about this)

**Comment by whitequark** [comment]
This broke compatibility with Python 3.6, but that series is end-of-life and we can drop support for it.
