### ISSUE TITLE
How to index particular bit of a Signal with another Signal?

### ISSUE THREAD

**Issue by YathinKumar11** [amaranth-lang/amaranth#708]
x = Signal(5)
x.eq(5)
y = Signal(5)
y.eq(10)

Now y[x] gives an error saying that a bit of a signal cannot be indexed with another signal. How can I make this possible? 
Is there any way to get the value that the Signal holds as an integer??

**Comment by andresdemski** [comment]
I think you are looking for bit_select method: https://amaranth-lang.org/docs/amaranth/latest/lang.html#signals
```python
comb += y.bit_select(x, 1).eq(A)
```

**Comment by whitequark** [comment]
Yes. See https://amaranth-lang.org/docs/amaranth/latest/lang.html#bit-sequence-operators for more details.
