### ISSUE TITLE
`build_top.sh` is written with CRLF line endings on Windows

### ISSUE THREAD

**Issue by whitequark** [amaranth-lang/amaranth#732]
This breaks it on *nix.

**Comment by whitequark** [comment]
Tentatively fixed in https://github.com/amaranth-lang/amaranth/commits/issue-732.

**Comment by whitequark** [comment]
@VioletEternity can you check this on Windows, please?

**Comment by VioletEternity** [comment]
I've tested that Amaranth-generated designs written with LF line endings synthesize fine with YoWASP Yosys and Vivado. Let me know if you'd like me to check any other toolchains.

**Comment by whitequark** [comment]
I think that's probably good enough. I'll leave a changelog entry in case some of the other vendor toolchains have issues with files with LF endings and then we can address it (which I **really hope** we won't need to).
