### ISSUE TITLE
Potential improvement for how FSM handles combinational signals

### ISSUE THREAD

**Issue by jjsuperpower** [amaranth-lang/amaranth#743]
I believe I have a potential improvement for how Amaranth handles combinational assignments in `FSM` class.  Please note when I refer to FSM I mean Finite State Machine. When I refer to `FSM` I am referring to the `FSM` class provided by the Amaranth library.

I created an FSM implementation has two states, one input, a synchronous output (Moore output), and a combinational output (Mealy Output). One state modifies the assigns the signals, the other does nothing. When tested with synchronous signal assignment, it behaves just like other HDL languages. However, when one testing with combinational signal assignment. It allows for an asynchronous output only when in the state that assigns the signals. When not in the state that is assigning the signal, the signal is assigned its reset value. While this not a bug as this occurs when implementing an FSM using a case statement in Amaranth, I think it would be a nice feature to add support for combinational statements to not be set to their reset values in a state that does not explicitly modify the signal for Amaranths FSM class.

I am requesting this be looked into as a potential improvement.
BTW big thank you to the Amaranth team and contributors.

P.S.
For anyone that might run into this issue, my current workaround is to just assign the combinational signal in every state. I have heard about the method `ongoing()` found [here](https://github.com/amaranth-lang/amaranth/blob/main/amaranth/hdl/dsl.py) that may also be a workaround, but I have not found any documentation for it, nor tested it

### Implementation using Amaranth FSM class 

![Screenshot_20230205_200036](https://user-images.githubusercontent.com/46900092/216867476-83cf7be2-35aa-4137-aa65-949710592e69.png)

### Example code

```python
from amaranth import *
from amaranth.sim import Settle, Delay, Simulator
from enum import Enum

class STATE_TABLE(Enum):
    STATE_0 = 0
    STATE_1 = 1


class Amaranth_FSM(Elaboratable):
    def __init__(self):
        
        self.in_1 = Signal()
        self.change_state = Signal()
        self.out_sync = Signal()
        self.out_comb = Signal()
    
    def elaborate(self, platform):
        m = Module()

        with m.FSM() as fsm:
            with m.State(STATE_TABLE.STATE_0):
                m.d.sync += self.out_sync.eq(self.in_1)
                m.d.comb += self.out_comb.eq(self.in_1)
                with m.If(self.change_state):
                    m.next = STATE_TABLE.STATE_1

            with m.State(STATE_TABLE.STATE_1):
                # Do nothing
                with m.If(self.change_state):
                    m.next = STATE_TABLE.STATE_0

        return m
    
  
def test_Amaranth_FSM():
    dut = Amaranth_FSM()

    def proc():
        yield dut.in_1.eq(0)
        yield dut.change_state.eq(0)
        yield Settle()
        yield Delay(5e-7)
        yield dut.in_1.eq(1)
        yield Settle()
        yield dut.change_state.eq(1)
        yield
        yield
        yield
        yield

    sim = Simulator(dut)
    sim.add_clock(1e-6)
    sim.add_sync_process(proc)

    with sim.write_vcd('Amaranth_FSM.vcd', 'Amaranth_FSM.gtkw'):    # get name of caller function
        sim.run()


if __name__ == "__main__":
    test_Amaranth_FSM()
```

**Comment by whitequark** [comment]
It is unclear exactly what is being requested. In any case, such a substantial change would require an RFC to proceed. I will suggest you discuss your proposed improvement on our IRC/Matrix/Discord channel with other contributors to formulate a clearer proposal.

As it is I do not see what action could be taken on this issue, so I will close it.
