### ISSUE TITLE
Implement RFC 10: Move `Repl` to `Value.replicate`

### ISSUE THREAD

**Issue by whitequark** [amaranth-lang/amaranth#770]
[RFC text](https://amaranth-lang.org/rfcs/0010-move-repl-to-value.html)
- [x] Add `Value.replicate`
  - [x] Update documentation
- [x] Deprecate `Repl` in 0.4
- [ ] Remove `Repl` in a later version

**Comment by charlottia** [comment]
o/ Would be happy to put together if desired.

**Comment by whitequark** [comment]
That would be great!

**Comment by charlottia** [comment]
Sweet, on my list for tomorrow! ✌️

**Comment by whitequark** [comment]
This wasn't actually completed--`Repl` is still there in `main`.
