### ISSUE TITLE
Docstring for View not updated after the RFC 15 commit

### ISSUE THREAD

**Issue by tilk** [amaranth-lang/amaranth#789]
The RFC 15 commit changed the View's constructor so that it no longer creates its own storage when it is not provided. The docstring, however, still refers to the previous version. This discrepancy appears on the public documentation page, which is confusing.

**Comment by whitequark** [comment]
> The RFC 15 commit changed the View's constructor so that it no longer creates its own storage when it is not provided. The docstring, however, still refers to the previous version.

This is actually because the RFC 15 implementation isn't merged yet!

**Comment by whitequark** [comment]
Closing in favor of https://github.com/amaranth-lang/amaranth/pull/791.
