### ISSUE TITLE
RecursionError in back.rtlil when compiling assignments with many operands

### ISSUE THREAD

**Issue by jfng** [amaranth-lang/amaranth#839]
Repro:
```python3
from amaranth import *
from amaranth.back import rtlil

N = 200

m = Module()
a = Signal()

a_fanin = 0
for i in range(N):
    a_fanin |= Const(1)

m.d.comb += a.eq(a_fanin)

print(rtlil.convert(m, ports=(a,)))
```

Output ([trace.txt](https://github.com/amaranth-lang/amaranth/files/12076895/trace.txt)):
```
RecursionError: maximum recursion depth exceeded
```

This example works when lowering `N` or increasing the CPython recursion limit (1000 on my machine).

**Comment by whitequark** [comment]
This is a known issue--I don't think we'll be able to address it without a rewrite of the RTLIL backend.

**Comment by whitequark** [comment]
This is no longer a problem with the new IR.
