### ISSUE TITLE
Implement RFC 18: Reorganize vendor platforms

### ISSUE THREAD

**Issue by whitequark** [amaranth-lang/amaranth#873]
RFC: https://amaranth-lang.org/rfcs/0018-reorganize-vendor-platforms.html
- [x] Reorganize vendor platforms: https://github.com/amaranth-lang/amaranth/pull/887
- [x] Remove deprecated names for platforms: https://github.com/amaranth-lang/amaranth/pull/1002

**Comment by gatecat** [comment]
Some implementation questions I have:

  - how should the lazy loading work? just checking all the vendor modules to see which one the class is in, or having a class->module dict in the `__init__.py`? (not sure if there's a standard python paradigm here I just don't know and couldn't immediately find)
   - do we need backwards compatibility?
   - in amaranth-boards there's a bunch of `from amaranth.vendor.lattice_ecp5 import *`, this would be refactored to specific imports like `from amaranth.vendor import LatticeECP5Platform`?

**Comment by whitequark** [comment]
> * having a class->module dict in the __init__.py?

I'm perfectly happy to have something like:

```python
def __getattr__(self, name):
    if name == "XilinxPlatform":
        from ._xilinx import XilinxPlatform as platform_cls
    elif name == "...":
        ...
    return platform_cls
```

> * do we need backwards compatibility?

Yes. Please leave modules like `vendor.xilinx` which just import the right class, and issue a deprecation warning. They will be removed after Amaranth 0.4 is released.

> * in amaranth-boards there's a bunch of `from amaranth.vendor.lattice_ecp5 import *`, this would be refactored to specific imports like `from amaranth.vendor import LatticeECP5Platform`?

Yes
