### ISSUE TITLE
Possible inconsistency in FlippedSignature

### ISSUE THREAD

**Issue by nelgau** [amaranth-lang/amaranth#914]
I may have found an inconsistency in `lib.wiring` by creating a component with an incoming wishbone bus. It appears to be an issue with how Amaranth creates interfaces for flipped signatures (and not with `amaranth-soc`'s wishbone implementation). Although the result was unexpected, I'm unsure of whether `lib.wiring`'s design actually supports this kind of access. Please let me know if I'm misusing something here.

The original issue can be reproduced like so:

```python
from amaranth import *
from amaranth.lib.wiring import In, Out, Component
from amaranth_soc import wishbone

class BusComponent(Component):
    output: Out(wishbone.bus.Signature(addr_width=32, data_width=32))
    input:  In(wishbone.bus.Signature(addr_width=32, data_width=32))

c = BusComponent()

print(type(c.output))
print(type(c.input))

c.output.addr_width
c.input.addr_width
```

Result:

```
<class 'amaranth_soc.wishbone.bus.Interface'>
<class 'amaranth.lib.wiring.Interface'>
Traceback (most recent call last):
[...]
    c.input.addr_width
AttributeError: 'Interface' object has no attribute 'addr_width'
```

As expected, the `c.output` attribute is a `wishbone.bus.Interface`. This is because `wishbone.bus.Signature` overrides the `create` method [here](https://github.com/amaranth-lang/amaranth-soc/blob/c5e1e6606a9452601c274e3e48cda8dbcf353b96/amaranth_soc/wishbone/bus.py#L180-L190) to return a wishbone-specific interface subclass. On the other hand, the `c.input` attribute is a simple `wiring.Interface`, which doesn't forward attribute access to the wishbone implementation. As a result, it isn't possible to access the `addr_width` attribute on the incoming bus. I found that surprising and unexpected.

Flipped interfaces don't seem to be affected, only interfaces created from flipped signatures:

```python
from amaranth import *
from amaranth.lib import wiring
from amaranth_soc import wishbone

wishbone.bus.Interface(addr_width=32, data_width=32).addr_width
wiring.flipped(wishbone.bus.Interface(addr_width=32, data_width=32)).addr_width

wishbone.bus.Signature(addr_width=32, data_width=32).create().addr_width
wishbone.bus.Signature(addr_width=32, data_width=32).flip().create().addr_width
```

Result:

```
Traceback (most recent call last):
    wishbone.bus.Signature(addr_width=32, data_width=32).flip().create().addr_width
AttributeError: 'Interface' object has no attribute 'addr_width'
```

**Comment by nelgau** [comment]
One possible solution would be to implement `FlippedSignature.create` to return the flipped interface constructed from the unflipped signature. After implementing it as below, the above reproductions appear to work correctly.

```python
class FlippedSignature:
    # ...
    def create(self, *, path=()):
        return flipped(self.__unflipped.create(path=path))
```

Is there a better way to achieve the same effect?

**Comment by whitequark** [comment]
I think this is just a bug! We will look into your proposed solution. Thank you for filing it ^^
