### ISSUE TITLE
`Signature.is_compliant()` should ensure that its argument is an interface object

### ISSUE THREAD

**Issue by jfng** [amaranth-lang/amaranth#935]
It currently works with any Python object with a matching set of attributes.

**Comment by zyp** [comment]
Remember that any Python object with a signature and a matching set of attributes *is* an interface. The RFC explicitly states that they don't have to inherit from `amaranth.lib.wiring.Interface`:

> Any object can be an interface object if it has the appropriate signature property. However, an amaranth.lib.wiring.Interface class is introduced, serving two purposes: instantiating interfaces from an anonymous signature, and serving as a convenient base class for custom interface classes.

**Comment by whitequark** [comment]
@jfng IIRC what we discussed was ensuring that `connect()` calls `is_compliant()` or something? Do I misremember our discussion?

**Comment by whitequark** [comment]
This wasn't what we discussed and what I think we discussed seems to be already implemented, so I'm closing this issue.

**Comment by whitequark** [comment]
I figured out what this issue was supposed to be about. Right now, `Signature.is_compliant(sig, obj)` only checks that `obj` has all the attributes that `sig` requires. It does not check that `obj` has a `signature` attribute and that `sig == obj.signature`. This should be fixed.
