### ISSUE TITLE
Wiring library not suitable for memory-mapped buses

### ISSUE THREAD

**Issue by tilk** [amaranth-lang/amaranth#984]
I'm working on removing dependencies on records in the [Coreblocks](https://github.com/kuznia-rdzeni/coreblocks) codebase. Among other uses, we are using records for connecting modules using the Wishbone bus (and, in the future, other buses). We handled slave-to-master signals by using the `include` and `exclude` arguments of `Record.connect`, and connecting the signals manually. I don't see a simple way to achieve this using the current interface API. A workaround could be to create interfaces with a subset of fields and use `connect` on them. How is this supposed to be done?

**Comment by whitequark** [comment]
Amaranth SoC [includes](https://github.com/amaranth-lang/amaranth-soc/commit/9ffaf949d853467d32e3e19fc0d472de65e45427) a wiring-based `wishbone.Interface`, so clearly Amaranth is suitable for such buses (and indeed `lib.wiring` was developed with these in mind). Unfortunately, you have not provided enough context for me to understand the specific problem you're facing, so I cannot help you resolve the source of your frustration.

**Comment by tilk** [comment]
Thank you for providing example code and design rationale. After consideration, I will provide further details or close the issue.

**Comment by tilk** [comment]
The linked code just doesn't use `connect`, and does the connecting manually using `eq`.

**Comment by whitequark** [comment]
@tilk Ah, yes. `wiring.connect()` is intended for making connections at e.g. the toplevel; in the *implementation* of something like a Wishbone arbiter or decoder you would use `.eq()` as usual.
